# main menu
[[main]]
name = "Hem"
url = "/"
weight = 1

#[[main]]
#name = "Blogg"
#url = "blog/"
#weight = 2

[[main]]
name = "Pris"
url = "pricing/"
weight = 3

[[main]]
name = "Kontakt"
url = "contact/"
weight = 4

#[[main]]
#name = "FAQ"
#url = "faq/"
#weight = 5

# footer menu left
[[footer_left]]
name = "Om oss"
url = "#"

[[footer_left]]
name = "Kom igång"
url = "#"

#[[footer_left]]
#name = "Pris"
#url = "pricing/"


# footer menu middle
[[footer_middle]]
name = "Pris"
url = "pricing/"

#[[footer_middle]]
#name = "Platform"
#url = "#"

#[[footer_middle]]
#name = "Features"
#url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"

#[[footer_right]]
#name = "FAQ"
#url = "faq/"